BUILD_FINGERPRINT=motorola/eqs_ge/msi:14/U1SQS34.52-21-1-8/ad3814-1af678:user/release-keys
BUILD_DESCRIPTION=eqs_ge-user 14 U1SQS34.52-21-1-8 ad3814-1af678 release-keys
BUILD_SECURITY_PATCH_DATE=2024-06-01
BUILD_TAGS=release-keys
BUILD_TYPE=user
BUILD_VERSION_RELEASE=14
BUILD_VERSION_RELEASE_OR_CODENAME=14
DEBUGGABLE=0
PRODUCT_NAME=eqs_ge
